name: bandit-security-linter
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - name: Run bandit
        uses: tj-actions/bandit@0aed5b3da320e0f26781e5aecbbfc1d268ff07e2  # v5.5
        with:
          options: "-c bandit.yml -r"
